version: '3.7'
services:
  easypermit-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: easypermit-backend
    container_name: easypermit-backend
    # command: uvicorn main:app --reload
    ports:
      - "9000:9000"
    expose:
      - 9000
    env_file:
      - ./.env